// TASK-0050 — GAP-B: is there a reachable subject where E4 is OBTAINABLE and NON-ADVERSE?
//
// Authority: MSG-0167; implementation/operations/TASK-0050-gap-b-e4-subject.md;
// EPA-0006 §4.6 S6/S9/S10/S11, §4.12 gap 1 (the F15 nonexistent-pragma control),
// §4.13 GAP-B / EV5, §4.15 (the basis this probe must measure BEYOND).
//
// WHAT THIS PROBE IS
//   An enumeration of the E4 surfaces reachable through ONE test subject — the subject every
//   Shape-1 measurement in §4.11, §4.12 and §4.14 was taken on — followed, for every surface
//   found obtainable, by §4.15's adversity probe and its C1–C4 conditions.
//
// WHAT THIS PROBE IS NOT
//   It selects, adopts, ranks, deploys, implements and clears nothing. The subject is an EVIDENCE
//   INSTRUMENT, not a candidate (MSG-0141). It changes no gate and no verdict. It installs
//   nothing, spawns no process, opens no socket, and writes only inside its own directory.
//
// TWO DISCIPLINES CARRIED FROM THE RECORD, NOT INVENTED HERE
//   1. F15 / §4.12 gap 1 — every instrument is run against a control that CERTAINLY does not
//      exist, because without one "the instrument reported nothing" and "the instrument was never
//      running" are the same observation.
//   2. §4.15 — every instrument is run DISARMED before ARMED, and a disarmed run that is not
//      silent voids that instrument's result.
//
// MSG-0156: a negative control's finding may NEVER be reported as a finding about the subject.
// Control results are therefore kept in their own structurally separate section throughout.

import { DatabaseSync } from 'node:sqlite';
import { readdirSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';

// ---------------------------------------------------------------------------------------------
// Markers. Two of them, deliberately distinct, so that a hit can be attributed to the path that
// produced it rather than to "the probe used a marker somewhere".
// ---------------------------------------------------------------------------------------------
const MARK_PARAM  = 'ZZ-UNAUTHORIZED-PASSAGE-TEXT-ZZ';  // §4.15's marker, bound as a PARAMETER
const MARK_INLINE = 'ZZ-UNAUTH-INLINE-TEXT-ZZ';         // the same text path, INLINED instead
const NONEXISTENT_PRAGMA = 'zzz_task_0050_pragma_that_certainly_does_not_exist';
const NONEXISTENT_VTAB   = 'zzz_task_0050_vtab_that_certainly_does_not_exist';

const out = [];
const say = (s = '') => { out.push(s); console.log(s); };
const hr  = (t) => { say(''); say('='.repeat(94)); say(t); say('='.repeat(94)); };
const sub = (t) => { say(''); say('--- ' + t + ' ' + '-'.repeat(Math.max(0, 88 - t.length))); };

function attempt(fn) {
  try { return { ok: true, value: fn() }; }
  catch (e) { return { ok: false, error: `${e.name}: ${e.message}` }; }
}

// ---------------------------------------------------------------------------------------------
// Fixture — §4.15's shape: 200 rows, 100 of them unauthorized and carrying the marker.
// The counts matter: §4.15 reported "200 examined, 100 returned, 1 trace entry", which is the
// C4 observation. This probe must be able to make the same comparison.
// ---------------------------------------------------------------------------------------------
function buildFixture(db) {
  db.exec(`CREATE TABLE chunk (id INTEGER PRIMARY KEY, scope TEXT NOT NULL, body TEXT NOT NULL)`);
  const ins = db.prepare(`INSERT INTO chunk (id, scope, body) VALUES (?, ?, ?)`);
  for (let i = 0; i < 100; i++) ins.run(i + 1, 'authorized', `authorized body ${i}`);
  for (let i = 0; i < 100; i++) ins.run(i + 101, 'unauthorized', `${MARK_PARAM} body ${i}`);
  db.exec(`CREATE INDEX idx_chunk_body ON chunk(body)`);
}

hr('TASK-0050 · E4 surface enumeration on the Shape-1 subject · GAP-B');
say(`generated by implementation/probes/TASK-0050/probe.mjs`);
say(`no install · no subprocess · no network · in-memory database only`);

// =============================================================================================
// S0 — Subject identity. Engine build AND language binding, stated separately, as §4.15's
//      table does. The binding is the variable that changed E4's obtainability last time, so it
//      is enumerated and never assumed.
// =============================================================================================
hr('S0 — SUBJECT IDENTITY (engine build and language binding stated separately)');

const db = new DatabaseSync(':memory:');
buildFixture(db);

const ver = db.prepare('SELECT sqlite_version() AS v, sqlite_source_id() AS s').get();
say(`language binding      : node:sqlite (Node.js built-in)`);
say(`runtime               : Node ${process.version}  (${process.platform} ${process.arch})`);
say(`engine                : SQLite ${ver.v}`);
say(`engine source id      : ${ver.s}`);
say(`database location     : ${JSON.stringify(attempt(() => db.location()).value ?? null)}  (":memory:" — no file, so no engine-written artefact to read)`);

// =============================================================================================
// S1 — The surface, ENUMERATED rather than assumed. §4.15 enumerated 42 public Connection names
//      and named the 3 that were present; this does the same for this binding's classes.
// =============================================================================================
hr('S1 — THE SURFACE, ENUMERATED RATHER THAN ASSUMED');

const sqliteMod = await import('node:sqlite');
const LOGGISH = /trace|log|profile|scanstat|authoriz|progress|hook|callback|debug|explain|instrument/i;

function enumerateNames(label, obj) {
  if (!obj) { say(`${label}: NOT PRESENT`); return []; }
  const proto = typeof obj === 'function' ? obj.prototype : Object.getPrototypeOf(obj);
  const names = new Set();
  for (const n of Object.getOwnPropertyNames(obj)) names.add(n);
  if (proto) for (const n of Object.getOwnPropertyNames(proto)) names.add(n);
  const list = [...names].filter(n => !['length', 'name', 'prototype', 'constructor'].includes(n)).sort();
  const hits = list.filter(n => LOGGISH.test(n));
  say(`${label}`);
  say(`   members (${list.length}): ${list.join(', ') || '(none)'}`);
  say(`   log/trace/profile-shaped members: ${hits.length ? hits.join(', ') : 'NONE'}`);
  return hits;
}

sub('module exports');
say(`node:sqlite exports (${Object.keys(sqliteMod).length}): ${Object.keys(sqliteMod).sort().join(', ')}`);

const classHits = [];
sub('class surfaces');
for (const name of ['DatabaseSync', 'StatementSync', 'Session', 'StatementResultingChanges']) {
  classHits.push(...enumerateNames(`${name}`, sqliteMod[name]));
}
sub('live instance surfaces (a class may expose nothing and an instance still carry a member)');
classHits.push(...enumerateNames('db (live DatabaseSync instance)', db));
const liveStmt = db.prepare('SELECT id FROM chunk WHERE scope = ?');
classHits.push(...enumerateNames('stmt (live StatementSync instance)', liveStmt));

sub('the specific C-API entry points E4 would need, each checked by NAME rather than assumed');
const CAPI = ['sqlite3_trace_v2', 'trace', 'traceV2', 'setTrace', 'profile', 'setProfile',
              'config_log', 'configLog', 'setLogger', 'log',
              'stmt_scanstatus', 'scanstatus', 'setAuthorizer', 'authorizer',
              'setProgressHandler', 'progressHandler', 'setUpdateHook', 'updateHook',
              'commitHook', 'rollbackHook', 'preupdateHook'];
const dbAll = new Set([...Object.getOwnPropertyNames(sqliteMod.DatabaseSync.prototype),
                       ...Object.getOwnPropertyNames(db)]);
for (const n of CAPI) say(`   ${n.padEnd(22)} : ${dbAll.has(n) ? '*** PRESENT ***' : 'ABSENT'}`);

say('');
say(`SUMMARY S1 — log/trace/profile-shaped members found anywhere on this binding: ${classHits.length ? [...new Set(classHits)].join(', ') : 'NONE'}`);

// =============================================================================================
// S2 — The build. §4.15 reported 43 compile options and named the three absences that matter.
// =============================================================================================
hr('S2 — THE BUILD (compile options)');

const opts = db.prepare('PRAGMA compile_options').all().map(r => Object.values(r)[0]);
say(`compile options (${opts.length}):`);
for (const o of opts) say(`   ${o}`);
sub('the three flags §4.15 named, plus the ones that would create a surface');
for (const flag of ['DEBUG', 'ENABLE_SQLLOG', 'ENABLE_STMT_SCANSTATUS', 'ENABLE_STMTVTAB',
                    'ENABLE_EXPLAIN_COMMENTS', 'ENABLE_DBPAGE_VTAB', 'ENABLE_DBSTAT_VTAB',
                    'ENABLE_BYTECODE_VTAB', 'OMIT_TRACE', 'ENABLE_NORMALIZE']) {
  const present = opts.some(o => o === flag || o === `SQLITE_${flag}`);
  say(`   ${flag.padEnd(26)} : ${present ? '*** PRESENT ***' : 'ABSENT'}`);
}

// =============================================================================================
// S3 — Tracing pragmas against the F15 CONTROL.
//      §4.12: SQLite silently ignores an unrecognised pragma, so "PRAGMA vdbe_trace=on returned
//      no error" is evidence of nothing. The control is a pragma that CERTAINLY does not exist;
//      a tracing pragma is believed only if it behaves DIFFERENTLY from it.
// =============================================================================================
hr('S3 — TRACING PRAGMAS AGAINST THE F15 NONEXISTENT-PRAGMA CONTROL');

function pragmaBehaviour(name) {
  const set = attempt(() => db.exec(`PRAGMA ${name} = 1`));
  const read = attempt(() => db.prepare(`PRAGMA ${name}`).all());
  return {
    setThrew: !set.ok, setError: set.error ?? null,
    readThrew: !read.ok, readError: read.error ?? null,
    readRows: read.ok ? JSON.stringify(read.value) : null,
  };
}

sub('CONTROL — kept structurally separate (MSG-0156: a control\'s finding is never a finding about the subject)');
const control = pragmaBehaviour(NONEXISTENT_PRAGMA);
say(`   PRAGMA ${NONEXISTENT_PRAGMA}`);
say(`      set threw : ${control.setThrew}${control.setError ? ' — ' + control.setError : ''}`);
say(`      read threw: ${control.readThrew}${control.readError ? ' — ' + control.readError : ''}`);
say(`      read rows : ${control.readRows}`);

sub('the tracing pragmas, each compared against that control');
const sig = (b) => `${b.setThrew}|${b.readThrew}|${b.readRows}`;
const controlSig = sig(control);
const pragmaRows = [];
for (const p of ['vdbe_trace', 'vdbe_listing', 'vdbe_addoptrace', 'vdbe_debug',
                 'parser_trace', 'sql_trace', 'stmt_scanstatus']) {
  const b = pragmaBehaviour(p);
  const identical = sig(b) === controlSig;
  pragmaRows.push({ p, identical });
  say(`   PRAGMA ${p.padEnd(18)} : ${identical ? 'IDENTICAL TO CONTROL -> INERT' : '*** DIFFERS FROM CONTROL -> INVESTIGATE ***'}   (set threw ${b.setThrew}, read rows ${b.readRows})`);
}
const inertCount = pragmaRows.filter(r => r.identical).length;
say('');
say(`SUMMARY S3 — ${inertCount} of ${pragmaRows.length} tracing pragmas are INERT (indistinguishable from a pragma that certainly does not exist).`);

// =============================================================================================
// S4 — Engine-emitted VIRTUAL TABLE surfaces. This is where this probe goes BEYOND §4.15:
//      §4.15 measured a statement TRACE (a callback), and found it adverse because it EXPANDS
//      the statement. A statement REGISTRY is a different surface of the same family, and
//      whether it expands is exactly the question the referral in the task file turns on.
// =============================================================================================
hr('S4 — ENGINE-EMITTED VIRTUAL-TABLE SURFACES (this is the class §4.15 did not measure)');

sub('module_list — what virtual table modules this build actually carries, enumerated');
const modList = attempt(() => db.prepare('PRAGMA module_list').all().map(r => Object.values(r)[0]).sort());
if (modList.ok) {
  say(`   modules (${modList.value.length}): ${modList.value.join(', ')}`);
  for (const m of ['sqlite_stmt', 'bytecode', 'tables_used', 'dbstat', 'sqlite_dbpage', 'stmt']) {
    say(`   ${m.padEnd(16)} : ${modList.value.includes(m) ? '*** PRESENT ***' : 'ABSENT'}`);
  }
} else {
  say(`   PRAGMA module_list unavailable — ${modList.error}`);
}

sub('CONTROL — a virtual table that certainly does not exist, kept structurally separate');
const vtabControl = attempt(() => db.prepare(`SELECT * FROM ${NONEXISTENT_VTAB}`).all());
say(`   SELECT * FROM ${NONEXISTENT_VTAB}`);
say(`      threw : ${!vtabControl.ok}${vtabControl.ok ? '' : ' — ' + vtabControl.error}`);
say(`   -> a surface is believed present only if it behaves DIFFERENTLY from this.`);

// The candidate surfaces, each probed for existence the same way.
const CANDIDATE_SURFACES = [
  { name: 'sqlite_stmt', sql: 'SELECT * FROM sqlite_stmt',
    what: 'the engine\'s own registry of prepared statements — a statement surface, like §4.15\'s trace' },
  { name: 'bytecode', sql: 'SELECT * FROM bytecode(\'SELECT 1\')',
    what: 'the engine\'s compiled program for a statement' },
  { name: 'tables_used', sql: 'SELECT * FROM tables_used(\'SELECT 1\')',
    what: 'the tables a statement reads' },
  // NO LIMIT, deliberately. An adversity scan over one row of a surface is a scan of one row,
  // not of the surface — the whole surface must be searched for passage text or the "0 hits"
  // means nothing.
  { name: 'dbstat', sql: 'SELECT * FROM dbstat',
    what: 'page-level storage statistics (every row scanned, not a sample)' },
  { name: 'sqlite_dbpage', sql: 'SELECT pgno FROM sqlite_dbpage LIMIT 1',
    what: 'raw page images (a DURABILITY artefact, not a log — DA-1/N6 territory, recorded for completeness)' },
];

sub('candidate surfaces, each tried and each distinguished from the control');
const obtainable = [];
for (const c of CANDIDATE_SURFACES) {
  const r = attempt(() => db.prepare(c.sql).all());
  const distinguished = r.ok || !/no such table|no such module|no such function/i.test(r.error ?? '');
  say(`   ${c.name.padEnd(16)} : ${r.ok ? '*** REACHABLE ***' : 'NOT REACHABLE'}  ${r.ok ? `(${r.value.length} row(s))` : '— ' + r.error}`);
  say(`   ${''.padEnd(16)}   ${c.what}`);
  say(`   ${''.padEnd(16)}   differs from the nonexistent-vtab control: ${distinguished ? 'YES' : 'NO — same shape as a table that does not exist'}`);
  if (r.ok) obtainable.push(c);
}

// =============================================================================================
// S5 — For every REACHABLE surface: run it DISARMED before ARMED, then run §4.15's ADVERSITY
//      probe against it. §4.15's specific probe reproduced exactly: unauthorized text bound as
//      a PARAMETER. A surface that survives that is NOT thereby clean, so inlined text and the
//      other reachable path are tested too.
// =============================================================================================
hr('S5 — DISARMED BEFORE ARMED, THEN THE ADVERSITY PROBE (§4.15 reproduced, then extended)');

function scanForMarkers(rows) {
  const text = JSON.stringify(rows);
  return {
    param:  (text.match(new RegExp(MARK_PARAM, 'g'))  || []).length,
    inline: (text.match(new RegExp(MARK_INLINE, 'g')) || []).length,
    bytes: text.length,
  };
}

const surfaceFindings = [];

for (const c of obtainable) {
  sub(`SURFACE: ${c.name}`);

  // --- DISARMED: the surface read on a connection where no marker-bearing statement has ever
  //     been prepared. If it is not silent, the instrument is voided for this run (§4.15).
  const clean = new DatabaseSync(':memory:');
  clean.exec('CREATE TABLE t (a)');
  const disarmedRead = attempt(() => clean.prepare(c.sql).all());
  const disarmed = disarmedRead.ok ? scanForMarkers(disarmedRead.value) : null;
  say(`   DISARMED (fresh connection, no unauthorized text has ever passed through it)`);
  say(`      readable        : ${disarmedRead.ok}${disarmedRead.ok ? '' : ' — ' + disarmedRead.error}`);
  if (disarmed) {
    say(`      rows            : ${disarmedRead.value.length}`);
    say(`      marker hits     : param ${disarmed.param}, inline ${disarmed.inline}`);
    say(`      silent?         : ${disarmed.param === 0 && disarmed.inline === 0 ? 'YES — instrument is valid for this run' : 'NO — INSTRUMENT VOIDED'}`);
  }
  clean.close();

  // --- ARMED path 1: §4.15's exact probe — unauthorized text bound as a PARAMETER.
  const armedDb = new DatabaseSync(':memory:');
  buildFixture(armedDb);
  const q1 = armedDb.prepare('SELECT id FROM chunk WHERE body = ?');
  const returned1 = q1.all(`${MARK_PARAM} body 7`);
  const armed1Read = attempt(() => armedDb.prepare(c.sql).all());
  const armed1 = armed1Read.ok ? scanForMarkers(armed1Read.value) : null;
  say(`   ARMED path 1 — unauthorized text bound as a PARAMETER (§4.15's exact probe)`);
  say(`      query           : SELECT id FROM chunk WHERE body = ?      [param = "${MARK_PARAM} body 7"]`);
  say(`      rows returned   : ${returned1.length}`);
  say(`      surface readable: ${armed1Read.ok}${armed1Read.ok ? '' : ' — ' + armed1Read.error}`);
  if (armed1) {
    say(`      surface rows    : ${armed1Read.value.length}`);
    say(`      marker hits     : *** param ${armed1.param} ***, inline ${armed1.inline}`);
    if (armed1.param > 0) {
      const sample = JSON.stringify(armed1Read.value).match(new RegExp('.{0,60}' + MARK_PARAM + '.{0,30}'));
      say(`      verbatim sample : ${sample ? sample[0] : '(n/a)'}`);
    }
  }

  // --- ARMED path 2: the same text INLINED. A surface that survives path 1 is not thereby clean.
  const inlineText = `${MARK_INLINE} body 7`;
  const q2 = attempt(() => armedDb.prepare(`SELECT id FROM chunk WHERE body = '${inlineText}'`).all());
  const armed2Read = attempt(() => armedDb.prepare(c.sql).all());
  const armed2 = armed2Read.ok ? scanForMarkers(armed2Read.value) : null;
  say(`   ARMED path 2 — the same text INLINED into the statement`);
  say(`      query           : SELECT id FROM chunk WHERE body = '${inlineText}'`);
  say(`      rows returned   : ${q2.ok ? q2.value.length : 'threw — ' + q2.error}`);
  say(`      surface readable: ${armed2Read.ok}${armed2Read.ok ? '' : ' — ' + armed2Read.error}`);
  if (armed2) {
    say(`      surface rows    : ${armed2Read.value.length}`);
    say(`      marker hits     : param ${armed2.param}, *** inline ${armed2.inline} ***`);
    if (armed2.inline > 0) {
      const sample = JSON.stringify(armed2Read.value).match(new RegExp('.{0,60}' + MARK_INLINE + '.{0,30}'));
      say(`      verbatim sample : ${sample ? sample[0] : '(n/a)'}`);
    }
  }

  // --- C4: does the surface record what the engine EXAMINED, or only the instruction?
  //     §4.15's numbers: 200 examined, 100 returned, 1 trace entry.
  const examined = 200;
  const returnedAll = armedDb.prepare("SELECT id FROM chunk WHERE scope = 'unauthorized'").all().length;
  const c4Read = attempt(() => armedDb.prepare(c.sql).all());
  say(`   C4 — instruction or examination?`);
  say(`      rows in fixture   : ${examined}   (100 authorized + 100 unauthorized)`);
  say(`      unauthorized rows : ${returnedAll}`);
  say(`      surface entries   : ${c4Read.ok ? c4Read.value.length : 'unreadable'}`);
  if (c4Read.ok && modList.ok && c.name === 'sqlite_stmt') {
    const cols = c4Read.value.length ? Object.keys(c4Read.value[0]) : [];
    say(`      surface columns   : ${cols.join(', ')}`);
    say(`      per-statement counters present: ${cols.filter(k => /nscan|nstep|nsort|naidx|run|reprep/.test(k)).join(', ') || 'none'}`);
    for (const row of c4Read.value) {
      say(`         [stmt] ${JSON.stringify(row)}`);
    }
  }

  surfaceFindings.push({
    name: c.name,
    disarmedSilent: disarmed ? (disarmed.param === 0 && disarmed.inline === 0) : null,
    paramHits: armed1 ? armed1.param : null,
    inlineHits: armed2 ? armed2.inline : null,
    entries: c4Read.ok ? c4Read.value.length : null,
  });

  armedDb.close();
}

// =============================================================================================
// S6 — Other reachable subjects on this machine. "Reachable" is established by LOOKING, not by
//      reading documentation about it (§4.6 S7.3's standard, applied to subjects rather than
//      placements). Nothing is installed and nothing is executed here — this is a read-only
//      filesystem enumeration of what a Node process could import WITHOUT an install.
// =============================================================================================
hr('S6 — OTHER SUBJECTS REACHABLE WITHOUT AN INSTALL (read-only enumeration)');

const ENGINE_HINTS = /sqlite|duckdb|libsql|postgres|pg$|mysql|lmdb|leveldb|rocksdb|lucene|tantivy|meilisearch|typesense|elastic|opensearch|orama|flexsearch|minisearch|lunr/i;
const searchRoots = [
  { label: 'repository node_modules', path: join(process.cwd(), 'node_modules') },
  { label: 'npm global node_modules', path: join(process.env.APPDATA ?? '', 'npm', 'node_modules') },
];
for (const root of searchRoots) {
  say('');
  say(`${root.label}: ${root.path}`);
  if (!root.path || !existsSync(root.path)) { say('   NOT PRESENT'); continue; }
  const entries = attempt(() => readdirSync(root.path).filter(n => !n.startsWith('.')));
  if (!entries.ok) { say(`   unreadable — ${entries.error}`); continue; }
  say(`   ${entries.value.length} package(s)`);
  const hits = entries.value.filter(n => ENGINE_HINTS.test(n));
  say(`   engine/index-shaped packages: ${hits.length ? hits.join(', ') : 'NONE'}`);
}

sub('built-in bindings this runtime carries, enumerated from the runtime itself');
const builtins = (await import('node:module')).builtinModules
  .filter(m => /sql|db|storage/i.test(m));
say(`   database-shaped built-ins: ${builtins.length ? builtins.join(', ') : 'NONE'}`);
say(`   -> node:sqlite is the only database engine this runtime supplies without an install.`);

sub('the extension path, named so it is not silently ignored');
const hasLoadExt = typeof db.loadExtension === 'function' || typeof db.enableLoadExtension === 'function';
say(`   DatabaseSync exposes loadExtension/enableLoadExtension: ${hasLoadExt ? 'YES' : 'NO'}`);
say(`   -> A loadable extension could in principle supply a trace surface. It would require a`);
say(`      COMPILED BINARY that is not present. That is an INSTALL, which TASK-0050's stop`);
say(`      conditions forbid: it is a BLOCKER to record, not a problem to solve locally.`);

// =============================================================================================
// S7 — Summary. Findings only; no verdict is invented here and none is upgraded.
// =============================================================================================
hr('S7 — SUMMARY OF WHAT WAS OBSERVED (findings only — verdicts belong to the record, not the probe)');

say(`subject                       : SQLite ${ver.v} via node:sqlite on Node ${process.version}`);
say(`log/trace/profile members     : ${classHits.length ? [...new Set(classHits)].join(', ') : 'NONE'}`);
say(`tracing pragmas INERT         : ${inertCount} of ${pragmaRows.length} (indistinguishable from the F15 control)`);
say(`reachable engine surfaces     : ${obtainable.length ? obtainable.map(c => c.name).join(', ') : 'NONE'}`);
say('');
for (const f of surfaceFindings) {
  say(`   ${f.name.padEnd(16)} disarmed-silent=${String(f.disarmedSilent).padEnd(5)} param-hits=${String(f.paramHits).padEnd(4)} inline-hits=${String(f.inlineHits).padEnd(4)} entries=${f.entries}`);
}
say('');
say('CONTROLS (structurally separate — MSG-0156: never reported as a finding about the subject)');
say(`   nonexistent pragma  : set threw ${control.setThrew}, read threw ${control.readThrew}, rows ${control.readRows}`);
say(`   nonexistent vtab    : threw ${!vtabControl.ok}`);

db.close();

// Write the output beside the probe, as every prior probe in this programme does.
const { writeFileSync } = await import('node:fs');
writeFileSync(new URL('./probe-output.txt', import.meta.url), out.join('\n') + '\n');
