-- =============================================================================
-- 0001_kernel_foundation
--
-- Work package : WP-0001 — PCI Kernel Foundation
-- Sources      : docs/knowledge/canonical-object-schema.md
--                docs/knowledge/provenance-model.md
--                SPEC-0005 Knowledge Object API
--                SPEC-0006 Audit and Evidence
--                SPEC-0007 Event Model
--                SPEC-0010 Tenant and Data Isolation
--                implementation/decisions/ADR-0016 (proposed) — isolation strategy
--
-- ⚠ NOT YET EXECUTED. No PostgreSQL instance was available during WP-0001 implementation.
--   See implementation/blockers/BLK-0001-no-execution-environment.md.
--
-- Design notes
-- ------------
-- * Every tenant-scoped table has PRIMARY KEY (tenant_id, id). Foreign keys therefore carry
--   tenant_id, so the database itself rejects a relationship whose endpoints are in different
--   tenants. Isolation does not depend on application code remembering a WHERE clause.
-- * `id` additionally carries a UNIQUE constraint so identifiers stay globally stable and
--   non-reusable (canonical-object-schema.md invariant 1).
-- * Historical tables (versions, provenance, audit, events) are append-only. UPDATE and DELETE
--   are revoked from the runtime role rather than merely avoided in code.
-- * Row-level security uses FORCE so the policy also binds the table owner. Without FORCE, a
--   deployment that runs the app as the owner silently loses tenant isolation.
-- =============================================================================

-- Transaction control belongs to the migration runner (src/cli/migrate.ts), which wraps each
-- file together with its schema_migrations bookkeeping. Do not add BEGIN/COMMIT here — that
-- would commit the DDL independently of the ledger entry and could leave the two disagreeing.

-- pgcrypto is not required: identifiers are generated by the application so that they exist
-- before the transaction commits and can be returned in events and audit records.

-- -----------------------------------------------------------------------------
-- Migration bookkeeping
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_migrations (
    version      text        PRIMARY KEY,
    applied_at   timestamptz NOT NULL DEFAULT now(),
    checksum     text        NOT NULL
);

COMMENT ON TABLE schema_migrations IS
    'Applied migration ledger. checksum detects edits to already-applied migrations.';

-- -----------------------------------------------------------------------------
-- Tenants
--
-- SPEC-0010: "Every customer-owned object has an explicit tenant/organization boundary."
-- A real table (rather than a bare string column) gives every tenant_id referential integrity.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tenants (
    id           text        PRIMARY KEY,
    display_name text        NOT NULL,
    -- 'customer' tenants hold customer-owned data; 'system' holds platform-owned objects,
    -- which SPEC-0010 requires to be explicitly classified and separately governed.
    kind         text        NOT NULL DEFAULT 'customer',
    created_at   timestamptz NOT NULL DEFAULT now(),
    active       boolean     NOT NULL DEFAULT true,

    CONSTRAINT tenants_id_slug     CHECK (id ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'),
    CONSTRAINT tenants_kind_valid  CHECK (kind IN ('customer', 'system'))
);

INSERT INTO tenants (id, display_name, kind)
VALUES ('system', 'PCI Platform (system-owned objects)', 'system')
ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Knowledge Objects — current state
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS knowledge_objects (
    tenant_id           text        NOT NULL REFERENCES tenants (id),
    id                  uuid        NOT NULL,

    type                text        NOT NULL,
    name                text        NOT NULL,
    status              text        NOT NULL,

    ownership_org       text        NOT NULL,
    ownership_owner     text        NOT NULL,
    classification      text        NOT NULL,

    created_at          timestamptz NOT NULL,
    updated_at          timestamptz NOT NULL,
    valid_from          timestamptz NULL,
    valid_to            timestamptz NULL,

    version             integer     NOT NULL,
    attributes          jsonb       NOT NULL DEFAULT '{}'::jsonb,

    created_by          text        NOT NULL,
    updated_by          text        NOT NULL,

    PRIMARY KEY (tenant_id, id),
    CONSTRAINT knowledge_objects_id_unique UNIQUE (id),

    CONSTRAINT knowledge_objects_type_valid CHECK (
        type IN ('Organization', 'Person', 'Service', 'Asset', 'Document', 'Policy', 'Agent')
    ),
    CONSTRAINT knowledge_objects_status_valid CHECK (
        status IN ('proposed', 'draft', 'reviewed', 'approved', 'active', 'deprecated', 'retired')
    ),
    CONSTRAINT knowledge_objects_classification_valid CHECK (
        classification IN ('public', 'internal', 'confidential', 'restricted')
    ),
    CONSTRAINT knowledge_objects_version_positive CHECK (version >= 1),
    CONSTRAINT knowledge_objects_name_not_blank   CHECK (length(btrim(name)) > 0),
    CONSTRAINT knowledge_objects_validity_ordered CHECK (
        valid_from IS NULL OR valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT knowledge_objects_attributes_object CHECK (jsonb_typeof(attributes) = 'object')
);

COMMENT ON TABLE knowledge_objects IS
    'Current state of canonical Knowledge Objects. History lives in knowledge_object_versions.';
COMMENT ON COLUMN knowledge_objects.attributes IS
    'Domain extension bag. Must never contain secrets (ADR-0009); enforced in src/domain/secret-guard.ts.';

CREATE INDEX IF NOT EXISTS knowledge_objects_tenant_type_idx
    ON knowledge_objects (tenant_id, type);
CREATE INDEX IF NOT EXISTS knowledge_objects_tenant_status_idx
    ON knowledge_objects (tenant_id, status);
CREATE INDEX IF NOT EXISTS knowledge_objects_tenant_owner_idx
    ON knowledge_objects (tenant_id, ownership_owner);
CREATE INDEX IF NOT EXISTS knowledge_objects_tenant_created_idx
    ON knowledge_objects (tenant_id, created_at, id);
-- Supports attribute containment queries without making the index the source of truth
-- (WP-0001: "Derived indexes must not become the canonical source of truth").
CREATE INDEX IF NOT EXISTS knowledge_objects_attributes_gin_idx
    ON knowledge_objects USING gin (attributes jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- Knowledge Object versions — append-only history
--
-- SPEC-0005 requires "Retrieve object history"; the lifecycle document requires that schema
-- changes preserve historical readability, so each row stores a whole snapshot rather than a
-- diff that would need today's schema to interpret.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS knowledge_object_versions (
    tenant_id    text        NOT NULL,
    object_id    uuid        NOT NULL,
    version      integer     NOT NULL,

    recorded_at  timestamptz NOT NULL,
    recorded_by  text        NOT NULL,
    change_kind  text        NOT NULL,
    snapshot     jsonb       NOT NULL,

    PRIMARY KEY (tenant_id, object_id, version),
    FOREIGN KEY (tenant_id, object_id) REFERENCES knowledge_objects (tenant_id, id),

    CONSTRAINT knowledge_object_versions_kind_valid CHECK (
        change_kind IN ('created', 'updated', 'state_changed', 'retired')
    ),
    CONSTRAINT knowledge_object_versions_version_positive CHECK (version >= 1)
);

CREATE INDEX IF NOT EXISTS knowledge_object_versions_lookup_idx
    ON knowledge_object_versions (tenant_id, object_id, version DESC);

-- -----------------------------------------------------------------------------
-- Relationships
--
-- canonical-object-schema.md invariant 5: relationships reference identifiers, never
-- duplicated object records. The composite foreign keys below make a cross-tenant
-- relationship a database error rather than an application oversight.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS relationships (
    tenant_id    text        NOT NULL REFERENCES tenants (id),
    id           uuid        NOT NULL,

    from_id      uuid        NOT NULL,
    to_id        uuid        NOT NULL,
    type         text        NOT NULL,

    created_at   timestamptz NOT NULL,
    created_by   text        NOT NULL,
    valid_from   timestamptz NULL,
    valid_to     timestamptz NULL,
    confidence   numeric(4,3) NULL,
    attributes   jsonb       NOT NULL DEFAULT '{}'::jsonb,

    PRIMARY KEY (tenant_id, id),
    CONSTRAINT relationships_id_unique UNIQUE (id),

    FOREIGN KEY (tenant_id, from_id) REFERENCES knowledge_objects (tenant_id, id),
    FOREIGN KEY (tenant_id, to_id)   REFERENCES knowledge_objects (tenant_id, id),

    CONSTRAINT relationships_no_self_reference CHECK (from_id <> to_id),
    CONSTRAINT relationships_confidence_range  CHECK (
        confidence IS NULL OR (confidence >= 0 AND confidence <= 1)
    ),
    CONSTRAINT relationships_validity_ordered CHECK (
        valid_from IS NULL OR valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT relationships_attributes_object CHECK (jsonb_typeof(attributes) = 'object'),
    CONSTRAINT relationships_type_valid CHECK (
        type IN (
            'OWNS','MANAGES','MEMBER_OF','REPORTS_TO','RESPONSIBLE_FOR',
            'LOCATED_IN','CONTAINS','INSTALLED_AT','CONNECTED_TO','ADJACENT_TO',
            'DEPENDS_ON','HOSTS','RUNS_ON','EXPOSES','CONNECTS_TO','MONITORED_BY',
            'SUPPORTS','PROVIDED_BY','AFFECTS','USED_BY','ASSIGNED_TO',
            'GOVERNED_BY','REQUIRES','AUTHORIZED_BY','APPROVED_BY','EXEMPTED_BY',
            'DOCUMENTED_BY','DERIVED_FROM','EVIDENCED_BY','RELATED_TO','SUPERSEDES',
            'GENERATED','RESOLVED_BY','CHANGED_BY','IMPACTS','TRIGGERS'
        )
    )
);

-- One active relationship of a given type between an ordered pair.
CREATE UNIQUE INDEX IF NOT EXISTS relationships_unique_edge_idx
    ON relationships (tenant_id, from_id, to_id, type);

CREATE INDEX IF NOT EXISTS relationships_from_idx ON relationships (tenant_id, from_id, type);
CREATE INDEX IF NOT EXISTS relationships_to_idx   ON relationships (tenant_id, to_id, type);

-- -----------------------------------------------------------------------------
-- Provenance — append-only
--
-- docs/knowledge/provenance-model.md; W3C PROV concepts (entity, activity, agent).
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS provenance_records (
    tenant_id        text        NOT NULL,
    id               uuid        NOT NULL,

    object_id        uuid        NOT NULL,
    object_version   integer     NOT NULL,

    source_id        text        NOT NULL,
    source_type      text        NOT NULL,
    source_location  text        NULL,

    observed_at      timestamptz NULL,
    ingested_at      timestamptz NOT NULL,
    transformation   text        NULL,

    actor_id         text        NOT NULL,
    connector        text        NULL,

    confidence       numeric(4,3) NULL,
    validation_state text        NOT NULL,
    evidence_ref     text        NULL,

    PRIMARY KEY (tenant_id, id),
    CONSTRAINT provenance_records_id_unique UNIQUE (id),
    FOREIGN KEY (tenant_id, object_id) REFERENCES knowledge_objects (tenant_id, id),

    CONSTRAINT provenance_source_type_valid CHECK (
        source_type IN (
            'human_input', 'service', 'agent_proposal', 'connector_observation',
            'document_extraction', 'imported_dataset', 'derived'
        )
    ),
    CONSTRAINT provenance_validation_state_valid CHECK (
        validation_state IN ('unvalidated', 'validated', 'rejected', 'superseded')
    ),
    CONSTRAINT provenance_confidence_range CHECK (
        confidence IS NULL OR (confidence >= 0 AND confidence <= 1)
    ),
    -- provenance-model.md: AI-generated statements are never authoritative merely because a
    -- model produced them. A model cannot self-certify, so this is enforced in the schema and
    -- not only in application code.
    CONSTRAINT provenance_agent_not_self_validated CHECK (
        source_type <> 'agent_proposal' OR validation_state <> 'validated'
    )
);

CREATE INDEX IF NOT EXISTS provenance_object_idx
    ON provenance_records (tenant_id, object_id, ingested_at);

-- -----------------------------------------------------------------------------
-- Audit — append-only evidence
--
-- SPEC-0006 Required Evidence. Every column below maps to one bullet of that list.
-- Audit records must not contain secrets; redaction happens in the application before write
-- (src/domain/secret-guard.ts).
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS audit_records (
    tenant_id         text        NOT NULL REFERENCES tenants (id),
    id                uuid        NOT NULL,
    occurred_at       timestamptz NOT NULL,

    actor_id          text        NOT NULL,
    actor_type        text        NOT NULL,
    delegated_by      text        NULL,

    action            text        NOT NULL,
    target_type       text        NOT NULL,
    target_id         text        NULL,

    policy_decision   text        NOT NULL,
    policy_version    text        NOT NULL,
    policy_reason     text        NOT NULL,

    correlation_id    uuid        NOT NULL,
    causation_id      text        NULL,

    outcome           text        NOT NULL,
    error_code        text        NULL,
    change_summary    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    resulting_version integer     NULL,

    PRIMARY KEY (tenant_id, id),
    CONSTRAINT audit_records_id_unique UNIQUE (id),

    CONSTRAINT audit_actor_type_valid CHECK (actor_type IN ('human', 'service', 'agent')),
    CONSTRAINT audit_outcome_valid CHECK (
        outcome IN ('success', 'denied', 'approval_required', 'error')
    ),
    CONSTRAINT audit_policy_decision_valid CHECK (
        policy_decision IN ('allow', 'deny', 'approval_required')
    ),
    CONSTRAINT audit_change_summary_object CHECK (jsonb_typeof(change_summary) = 'object')
);

COMMENT ON TABLE audit_records IS
    'Append-only audit evidence (SPEC-0006). UPDATE and DELETE are revoked from the runtime role.';

CREATE INDEX IF NOT EXISTS audit_records_time_idx        ON audit_records (tenant_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_records_actor_idx       ON audit_records (tenant_id, actor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_records_target_idx      ON audit_records (tenant_id, target_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_records_correlation_idx ON audit_records (tenant_id, correlation_id);
CREATE INDEX IF NOT EXISTS audit_records_action_idx      ON audit_records (tenant_id, action, occurred_at DESC);

-- -----------------------------------------------------------------------------
-- Events — transactional outbox
--
-- SPEC-0007. WP-0001 persists envelopes in the same transaction as the mutation they describe.
-- No broker, dispatcher, or subscription mechanism is in scope for this work package.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS events (
    tenant_id       text        NOT NULL REFERENCES tenants (id),
    id              uuid        NOT NULL,

    type            text        NOT NULL,
    occurred_at     timestamptz NOT NULL,
    producer        text        NOT NULL,
    produced_by     text        NOT NULL,

    subject_type    text        NOT NULL,
    subject_id      text        NOT NULL,
    related_ids     text[]      NOT NULL DEFAULT '{}',

    correlation_id  uuid        NOT NULL,
    causation_id    text        NULL,

    payload_version integer     NOT NULL,
    payload         jsonb       NOT NULL DEFAULT '{}'::jsonb,

    -- Outbox dispatch bookkeeping. Unused in WP-0001; present so a dispatcher can be added
    -- without a migration that would have to rewrite historical rows.
    published_at    timestamptz NULL,

    PRIMARY KEY (tenant_id, id),
    CONSTRAINT events_id_unique UNIQUE (id),
    CONSTRAINT events_payload_object CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT events_payload_version_positive CHECK (payload_version >= 1)
);

CREATE INDEX IF NOT EXISTS events_subject_idx     ON events (tenant_id, subject_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_correlation_idx ON events (tenant_id, correlation_id);
CREATE INDEX IF NOT EXISTS events_unpublished_idx ON events (tenant_id, occurred_at)
    WHERE published_at IS NULL;

-- =============================================================================
-- Row-level security  (ADR-0016 layer 3)
--
-- The application sets `pci.tenant_id` transaction-locally before any statement runs.
-- current_setting(..., true) returns NULL when unset, so an unset GUC matches NO rows —
-- the failure mode is "see nothing", never "see everything".
--
-- FORCE binds the policy to the table owner as well. Without it, a deployment that runs the
-- application as the owning role silently loses tenant isolation.
-- =============================================================================

ALTER TABLE knowledge_objects          ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_objects          FORCE  ROW LEVEL SECURITY;
ALTER TABLE knowledge_object_versions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_object_versions  FORCE  ROW LEVEL SECURITY;
ALTER TABLE relationships              ENABLE ROW LEVEL SECURITY;
ALTER TABLE relationships              FORCE  ROW LEVEL SECURITY;
ALTER TABLE provenance_records         ENABLE ROW LEVEL SECURITY;
ALTER TABLE provenance_records         FORCE  ROW LEVEL SECURITY;
ALTER TABLE audit_records              ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_records              FORCE  ROW LEVEL SECURITY;
ALTER TABLE events                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE events                     FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON knowledge_objects;
CREATE POLICY tenant_isolation ON knowledge_objects
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

DROP POLICY IF EXISTS tenant_isolation ON knowledge_object_versions;
CREATE POLICY tenant_isolation ON knowledge_object_versions
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

DROP POLICY IF EXISTS tenant_isolation ON relationships;
CREATE POLICY tenant_isolation ON relationships
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

DROP POLICY IF EXISTS tenant_isolation ON provenance_records;
CREATE POLICY tenant_isolation ON provenance_records
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

DROP POLICY IF EXISTS tenant_isolation ON audit_records;
CREATE POLICY tenant_isolation ON audit_records
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

DROP POLICY IF EXISTS tenant_isolation ON events;
CREATE POLICY tenant_isolation ON events
    USING (tenant_id = current_setting('pci.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('pci.tenant_id', true));

-- =============================================================================
-- Runtime role grants
--
-- The runtime role (pci_app) is deliberately NOT the owner and must NOT hold BYPASSRLS or
-- SUPERUSER, or layer 3 above becomes inert. Roles are created by
-- deploy/compose/initdb/00-roles.sql, which runs as the cluster superuser.
--
-- Append-only tables grant INSERT and SELECT only. Tamper-evidence required by SPEC-0006 and
-- security-architecture.md is enforced by privilege, not by convention.
-- =============================================================================

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pci_app') THEN
        EXECUTE 'GRANT USAGE ON SCHEMA public TO pci_app';

        EXECUTE 'GRANT SELECT, INSERT, UPDATE ON knowledge_objects TO pci_app';
        EXECUTE 'GRANT SELECT ON tenants TO pci_app';

        -- Append-only: no UPDATE, no DELETE.
        EXECUTE 'GRANT SELECT, INSERT ON knowledge_object_versions TO pci_app';
        EXECUTE 'GRANT SELECT, INSERT ON provenance_records TO pci_app';
        EXECUTE 'GRANT SELECT, INSERT ON audit_records TO pci_app';
        EXECUTE 'GRANT SELECT, INSERT ON events TO pci_app';

        -- Relationships may be removed; that removal is itself audited.
        EXECUTE 'GRANT SELECT, INSERT, DELETE ON relationships TO pci_app';

        -- Explicitly revoke the destructive privileges on Knowledge Objects. Retirement is a
        -- lifecycle transition, never a delete (canonical-object-schema.md invariant 1).
        EXECUTE 'REVOKE DELETE ON knowledge_objects FROM pci_app';
        EXECUTE 'REVOKE UPDATE, DELETE ON knowledge_object_versions FROM pci_app';
        EXECUTE 'REVOKE UPDATE, DELETE ON provenance_records FROM pci_app';
        EXECUTE 'REVOKE UPDATE, DELETE ON audit_records FROM pci_app';
        EXECUTE 'REVOKE UPDATE, DELETE ON events FROM pci_app';
    ELSE
        RAISE NOTICE 'Role pci_app not present; skipping grants. Create it before running the service.';
    END IF;
END
$$;
